version: "2"

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - ineffassign
  settings:
    staticcheck:
      checks:
        - all
        - -QF1012
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
